### PR TITLE
Full Python3 compatibility + PEP8

### PR DESCRIPTION
**Pull request by raphael0202**
mitie.py should now be fully Python3 compatible. I've also reformatted the code such that it is compliant with PEP8, the coding style of the python community (https://www.python.org/dev/peps/pep-0008/)

### CODE REVIEW

**Comment by davisking** [comment]
`to_default_str_type` has only been called on some of the the strings coming out of MITIE.  Shouldn't it be needed for all of them?

**Comment by raphael0202** [comment]
Well it should be called on every string that comes from MITIE, I've spotted the remaining methods where `to_default_str_type` were not called (I've just added a commit to the PR). I'm only familiar with NER tagger, so if I've missed some piece of code where it should be called, don't hesitate to tell me.

**Comment by davisking** [comment]
Sweet, thanks for the PR :+1:

**Comment by avitale** [comment]
Hi,
After this commit I started getting an error from the to_bytes function.
The error seems to be that string.encode('utf-8') gets called on a utf string where string.encode('utf-8') was previously called. I am using Python 2.7.
I wrapped string.encode('utf-8') in a try/except and things started working again.

**Comment by davisking** [comment]
Cool.  Can you submit a pull request for this?

**Comment by avitale** [comment]
Sure, done

**Pull request merged**
